/**
 * Error Codes for Standardized Error Responses
 * BE-027: Error codes for common scenarios
 */

const ERROR_CODES = {
  // File Operations
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILE_ALREADY_EXISTS: 'FILE_ALREADY_EXISTS',
  FILE_CORRUPTED: 'FILE_CORRUPTED',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_TYPE_NOT_SUPPORTED: 'FILE_TYPE_NOT_SUPPORTED',
  FILE_COUNT_LIMIT_EXCEEDED: 'FILE_COUNT_LIMIT_EXCEEDED',
  FILE_NAME_INVALID: 'FILE_NAME_INVALID',
  FILE_STRUCTURE_INVALID: 'FILE_STRUCTURE_INVALID',
  FILE_MAGIC_BYTES_MISMATCH: 'FILE_MAGIC_BYTES_MISMATCH',
  
  // Permission & Authorization
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_PERMISSION: 'INVALID_PERMISSION',
  
  // Storage & Quota
  QUOTA_EXCEEDED: 'QUOTA_EXCEEDED',
  STORAGE_QUOTA_EXCEEDED: 'STORAGE_QUOTA_EXCEEDED',
  STORAGE_ERROR: 'STORAGE_ERROR',
  STORAGE_PATH_INVALID: 'STORAGE_PATH_INVALID',
  STORAGE_FILE_NOT_FOUND: 'STORAGE_FILE_NOT_FOUND',
  
  // Folder Operations
  FOLDER_NOT_FOUND: 'FOLDER_NOT_FOUND',
  FOLDER_ALREADY_EXISTS: 'FOLDER_ALREADY_EXISTS',
  FOLDER_NAME_INVALID: 'FOLDER_NAME_INVALID',
  
  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_DATE_FORMAT: 'INVALID_DATE_FORMAT',
  INVALID_INPUT: 'INVALID_INPUT',
  DESCRIPTION_TOO_LONG: 'DESCRIPTION_TOO_LONG',
  COMMENT_TOO_LONG: 'COMMENT_TOO_LONG',
  COLOR_FORMAT_INVALID: 'COLOR_FORMAT_INVALID',
  
  // Rate Limiting
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  CONCURRENT_UPLOAD_LIMIT_EXCEEDED: 'CONCURRENT_UPLOAD_LIMIT_EXCEEDED',
  
  // Database
  DATABASE_ERROR: 'DATABASE_ERROR',
  DATABASE_CONNECTION_ERROR: 'DATABASE_CONNECTION_ERROR',
  TRANSACTION_FAILED: 'TRANSACTION_FAILED',
  CONCURRENT_MODIFICATION: 'CONCURRENT_MODIFICATION',
  
  // Network & External Services
  NETWORK_ERROR: 'NETWORK_ERROR',
  STORAGE_SERVICE_ERROR: 'STORAGE_SERVICE_ERROR',
  EMAIL_SERVICE_ERROR: 'EMAIL_SERVICE_ERROR',
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
  
  // General
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  TIMEOUT: 'TIMEOUT',
  
  // Share Operations
  SHARE_NOT_FOUND: 'SHARE_NOT_FOUND',
  SHARE_EXPIRED: 'SHARE_EXPIRED',
  SHARE_MAX_DOWNLOADS_EXCEEDED: 'SHARE_MAX_DOWNLOADS_EXCEEDED',
  
  // Comments
  COMMENT_NOT_FOUND: 'COMMENT_NOT_FOUND',
  PARENT_COMMENT_NOT_FOUND: 'PARENT_COMMENT_NOT_FOUND'
};

/**
 * Get HTTP status code for error code
 */
function getStatusCodeForErrorCode(errorCode) {
  const statusCodeMap = {
    [ERROR_CODES.UNAUTHORIZED]: 401,
    [ERROR_CODES.FORBIDDEN]: 403,
    [ERROR_CODES.PERMISSION_DENIED]: 403,
    [ERROR_CODES.NOT_FOUND]: 404,
    [ERROR_CODES.FILE_NOT_FOUND]: 404,
    [ERROR_CODES.FOLDER_NOT_FOUND]: 404,
    [ERROR_CODES.SHARE_NOT_FOUND]: 404,
    [ERROR_CODES.COMMENT_NOT_FOUND]: 404,
    [ERROR_CODES.BAD_REQUEST]: 400,
    [ERROR_CODES.VALIDATION_ERROR]: 400,
    [ERROR_CODES.INVALID_INPUT]: 400,
    [ERROR_CODES.INVALID_EMAIL]: 400,
    [ERROR_CODES.INVALID_DATE_FORMAT]: 400,
    [ERROR_CODES.FILE_NAME_INVALID]: 400,
    [ERROR_CODES.FOLDER_NAME_INVALID]: 400,
    [ERROR_CODES.COLOR_FORMAT_INVALID]: 400,
    [ERROR_CODES.DESCRIPTION_TOO_LONG]: 400,
    [ERROR_CODES.COMMENT_TOO_LONG]: 400,
    [ERROR_CODES.CONFLICT]: 409,
    [ERROR_CODES.FILE_ALREADY_EXISTS]: 409,
    [ERROR_CODES.FOLDER_ALREADY_EXISTS]: 409,
    [ERROR_CODES.CONCURRENT_MODIFICATION]: 409,
    [ERROR_CODES.RATE_LIMIT_EXCEEDED]: 429,
    [ERROR_CODES.CONCURRENT_UPLOAD_LIMIT_EXCEEDED]: 429,
    [ERROR_CODES.QUOTA_EXCEEDED]: 403,
    [ERROR_CODES.STORAGE_QUOTA_EXCEEDED]: 403,
    [ERROR_CODES.FILE_COUNT_LIMIT_EXCEEDED]: 403,
    [ERROR_CODES.FILE_TOO_LARGE]: 403,
    [ERROR_CODES.TIMEOUT]: 408,
    [ERROR_CODES.INTERNAL_SERVER_ERROR]: 500,
    [ERROR_CODES.DATABASE_ERROR]: 500,
    [ERROR_CODES.DATABASE_CONNECTION_ERROR]: 503,
    [ERROR_CODES.STORAGE_ERROR]: 500,
    [ERROR_CODES.STORAGE_SERVICE_ERROR]: 503,
    [ERROR_CODES.EMAIL_SERVICE_ERROR]: 500,
    [ERROR_CODES.NETWORK_ERROR]: 503,
    [ERROR_CODES.EXTERNAL_SERVICE_ERROR]: 503
  };
  
  return statusCodeMap[errorCode] || 500;
}

module.exports = {
  ERROR_CODES,
  getStatusCodeForErrorCode
};

