import React from 'react';

export interface ResumeEditorProps {
  resumeFileName: string;
  setResumeFileName: (name: string) => void;
  sectionOrder: string[];
  sectionVisibility: Record<string, boolean>;
  customSections: any[];
  resumeData: any;
  setResumeData: (data: any) => void;
  fontFamily: string;
  setFontFamily: (font: string) => void;
  fontSize: string;
  setFontSize: (size: string) => void;
  lineSpacing: string;
  setLineSpacing: (spacing: string) => void;
  sectionSpacing: string;
  setSectionSpacing: (spacing: string) => void;
  margins: string;
  setMargins: (margins: string) => void;
  headingStyle: string;
  setHeadingStyle: (style: string) => void;
  bulletStyle: string;
  setBulletStyle: (style: string) => void;
  onToggleSection: (section: string) => void;
  onMoveSection: (index: number, direction: 'up' | 'down') => void;
  onShowAddSectionModal: () => void;
  onDeleteCustomSection: (id: string) => void;
  onUpdateCustomSection: (id: string, content: string) => void;
  onGenerateSmartFileName: () => string;
  onResetToDefault: () => void;
  renderSection: (section: string) => React.ReactNode;
  showAddFieldModal: boolean;
  setShowAddFieldModal: (show: boolean) => void;
  customFields: Array<{ id: string; name: string; icon?: string; value?: string }>;
  setCustomFields: (fields: Array<{ id: string; name: string; icon?: string; value?: string }>) => void;
  newFieldName: string;
  setNewFieldName: (name: string) => void;
  newFieldIcon: string;
  setNewFieldIcon: (icon: string) => void;
  onAddCustomField: () => void;
  selectedTemplateId?: string | null;
  onTemplateApply?: (templateId: string) => void;
  addedTemplates?: string[];
  onRemoveTemplate?: (templateId: string) => void;
  onAddTemplates?: (templateIds: string[]) => void;
  onNavigateToTemplates?: () => void;
  isSidebarCollapsed?: boolean;
  onToggleSidebar?: () => void;
  resumes?: Array<{ id: string; name: string; fileName?: string; templateId?: string | null }>;
  activeResumeId?: string | null;
  onResumeSwitch?: (resumeId: string) => void | Promise<void>;
  onResumeCreate?: () => void | Promise<void>;
  onResumeDelete?: (resumeId: string) => void | Promise<void>;
  isResumeListLoading?: boolean;
  maxResumes?: number;
}

